# seed_data.py
# Dados de teste usados para popular o banco SQLite local (data/app.db) na
# primeira execução do app, no lugar do Oracle corporativo original.

ESTADOS = [
    ("Acre", "AC"), ("Alagoas", "AL"), ("Amapá", "AP"), ("Amazonas", "AM"),
    ("Bahia", "BA"), ("Ceará", "CE"), ("Distrito Federal", "DF"),
    ("Espírito Santo", "ES"), ("Goiás", "GO"), ("Maranhão", "MA"),
    ("Mato Grosso", "MT"), ("Mato Grosso do Sul", "MS"), ("Minas Gerais", "MG"),
    ("Pará", "PA"), ("Paraíba", "PB"), ("Paraná", "PR"), ("Pernambuco", "PE"),
    ("Piauí", "PI"), ("Rio de Janeiro", "RJ"), ("Rio Grande do Norte", "RN"),
    ("Rio Grande do Sul", "RS"), ("Rondônia", "RO"), ("Roraima", "RR"),
    ("Santa Catarina", "SC"), ("São Paulo", "SP"), ("Sergipe", "SE"),
    ("Tocantins", "TO"),
]

CLASSES_PROCESSO = [
    ("Ação Trabalhista",), ("Ação Civil",), ("Ação Penal",),
    ("Ação Tributária",), ("Ação Administrativa",), ("Ação Empresarial",),
    ("Ação Constitucional",),
]

CAMINHO_PROCESSO = [
    ("Petição Inicial",), ("Intimação",), ("Contestação",),
    ("Notificação",), ("Conciliação",), ("Sentença",), ("Apelação",),
]

DATAJUD_ENDPOINTS = [
    ('Tribunais Superiores', 'Tribunal Superior do Trabalho', 'https://api-publica.datajud.cnj.jus.br/api_publica_tst/_search'),
    ('Tribunais Superiores', 'Tribunal Superior Eleitoral', 'https://api-publica.datajud.cnj.jus.br/api_publica_tse/_search'),
    ('Tribunais Superiores', 'Tribunal Superior de Justiça', 'https://api-publica.datajud.cnj.jus.br/api_publica_stj/_search'),
    ('Tribunais Superiores', 'Tribunal Superior Militar', 'https://api-publica.datajud.cnj.jus.br/api_publica_stm/_search'),
    ('Justiça Federal', 'Tribunal Regional Federal da 1ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trf1/_search'),
    ('Justiça Federal', 'Tribunal Regional Federal da 2ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trf2/_search'),
    ('Justiça Federal', 'Tribunal Regional Federal da 3ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trf3/_search'),
    ('Justiça Federal', 'Tribunal Regional Federal da 4ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trf4/_search'),
    ('Justiça Federal', 'Tribunal Regional Federal da 5ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trf5/_search'),
    ('Justiça Federal', 'Tribunal Regional Federal da 6ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trf6/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça do Acre', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjac/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça de Alagoas', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjal/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça do Amazonas', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjam/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça do Amapá', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjap/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça da Bahia', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjba/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça do Ceará', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjce/_search'),
    ('Justiça Estadual', 'TJ do Distrito Federal e Territórios', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjdft/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça do Espírito Santo', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjes/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça do Goiás', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjgo/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça do Maranhão', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjma/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça de Minas Gerais', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjmg/_search'),
    ('Justiça Estadual', 'TJ do Mato Grosso de Sul', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjms/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça do Mato Grosso', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjmt/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça do Pará', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjpa/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça da Paraíba', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjpb/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça de Pernambuco', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjpe/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça do Piauí', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjpi/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça do Paraná', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjpr/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça do Rio de Janeiro', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjrj/_search'),
    ('Justiça Estadual', 'TJ do Rio Grande do Norte', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjrn/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça de Rondônia', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjro/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça de Roraima', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjrr/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça do Rio Grande do Sul', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjrs/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça de Santa Catarina', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjsc/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça de Sergipe', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjse/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça de São Paulo', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjsp/_search'),
    ('Justiça Estadual', 'Tribunal de Justiça do Tocantins', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjto/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 1ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt1/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 2ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt2/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 3ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt3/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 4ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt4/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 5ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt5/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 6ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt6/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 7ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt7/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 8ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt8/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 9ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt9/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 10ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt10/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 11ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt11/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 12ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt12/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 13ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt13/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 14ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt14/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 15ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt15/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 16ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt16/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 17ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt17/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 18ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt18/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 19ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt19/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 20ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt20/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 21ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt21/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 22ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt22/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 23ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt23/_search'),
    ('Justiça do Trabalho', 'Tribunal Regional do Trabalho da 24ª Região', 'https://api-publica.datajud.cnj.jus.br/api_publica_trt24/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral do Acre', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-ac/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral de Alagoas', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-al/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral do Amazonas', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-am/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral do Amapá', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-ap/_search'),
    ('Justiça Eleitoral', 'Tribunal de Justiça da Bahia', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-ba/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral do Ceará', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-ce/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral do Distrito Federal', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-dft/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral do Espírito Santo', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-es/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral do Goiás', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-go/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral do Maranhão', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-ma/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral de Minas Gerais', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-mg/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral do Mato Grosso de Sul', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-ms/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral do Mato Grosso', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-mt/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral do Pará', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-pa/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral da Paraíba', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-pb/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral de Pernambuco', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-pe/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral do Piauí', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-pi/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral do Paraná', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-pr/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral do Rio de Janeiro', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-rj/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral do Rio Grande do Norte', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-rn/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral de Rondônia', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-ro/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral de Roraima', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-rr/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral do Rio Grande do Sul', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-rs/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral de Santa Catarina', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-sc/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral de Sergipe', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-se/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral de São Paulo', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-sp/_search'),
    ('Justiça Eleitoral', 'Tribunal Regional Eleitoral do Tocantins', 'https://api-publica.datajud.cnj.jus.br/api_publica_tre-to/_search'),
    ('Justiça Militar', 'Tribunal Justiça Militar de Minas Gerais', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjmmg/_search'),
    ('Justiça Militar', 'Tribunal Justiça Militar do Rio Grande do Sul', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjmrs/_search'),
    ('Justiça Militar', 'Tribunal Justiça Militar de São Paulo', 'https://api-publica.datajud.cnj.jus.br/api_publica_tjmsp/_search'),
]

# numero_processo, classe_processo, rito_processo, nome_advogado, numero_oab,
# nome_cliente_empresa, caminho_processual, nome_juiz, estado_processo,
# valor_causa, valor_deferido_causa, valor_pago_causa, observacoes_clob,
# justica, tribunal
PROCESSOS_TESTE = [
    ("00001112320238260100", "Ação Trabalhista", "Ordinário", "Vitória Elisa Fernandes", "0099887766",
     "Comércio ABC Ltda", "Sentença", "João da Silva", "SP",
     15000.00, 12000.00, 12000.00, "Processo encerrado com acordo.",
     "Justiça do Trabalho", "Tribunal Regional do Trabalho da 2ª Região"),
    ("00002223420238260200", "Ação Civil", "Sumário", "Vitória Elisa Fernandes", "0099887766",
     "Maria Oliveira", "Contestação", "Ana Souza", "RJ",
     8500.50, 0.00, 0.00, "Aguardando resposta da parte ré.",
     "Justiça Estadual", "Tribunal de Justiça do Rio de Janeiro"),
    ("00003334520238260300", "Ação Tributária", "Ordinário", "Vitória Elisa Fernandes", "0099887766",
     "Indústria Nacional S/A", "Petição Inicial", "Carlos Pereira", "MG",
     120000.00, 0.00, 0.00, "Discussão sobre ICMS retido.",
     "Justiça Federal", "Tribunal Regional Federal da 6ª Região"),
    ("00004445620238260400", "Ação Empresarial", "Ordinário", "Vitória Elisa Fernandes", "0099887766",
     "Tech Solutions Ltda", "Conciliação", "Patrícia Lima", "SC",
     45000.00, 45000.00, 20000.00, "Acordo em andamento, pagamento parcelado.",
     "Justiça Estadual", "Tribunal de Justiça de Santa Catarina"),
    ("00005556720238260500", "Ação Penal", "Sumaríssimo", "Vitória Elisa Fernandes", "0099887766",
     "Ministério Público", "Intimação", "Roberto Nunes", "RS",
     0.00, 0.00, 0.00, "Audiência marcada para o próximo mês.",
     "Justiça Estadual", "Tribunal de Justiça do Rio Grande do Sul"),
    ("00006667820238260600", "Ação Constitucional", "Ordinário", "Vitória Elisa Fernandes", "0099887766",
     "Associação dos Moradores", "Apelação", "Fernanda Castro", "DF",
     30000.00, 18000.00, 0.00, "Recurso em análise no tribunal.",
     "Justiça Federal", "Tribunal Regional Federal da 1ª Região"),
]
