CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE,
    password VARCHAR2(100),
    data_creiacao DATE DEFAULT SYSDATE
);

insert into users(username, password)
values('admin', 'admin');

select * from users;