-- Criar tabela das classes de processos jurídicos 
CREATE TABLE classes_processo (
    classe_processo VARCHAR2(100) PRIMARY KEY
);

INSERT INTO classes_processo (classe_processo) VALUES ('Ação Trabalhista');
INSERT INTO classes_processo (classe_processo) VALUES ('Ação Civil');
INSERT INTO classes_processo (classe_processo) VALUES ('Ação Penal');
INSERT INTO classes_processo (classe_processo) VALUES ('Ação Tributária');
INSERT INTO classes_processo (classe_processo) VALUES ('Ação Administrativa');
INSERT INTO classes_processo (classe_processo) VALUES ('Ação Empresarial');
INSERT INTO classes_processo (classe_processo) VALUES ('Ação Constitucional');

select * from classes_processo



-- Criar tabela das classes de processos jurídicos 
CREATE TABLE caminho_processo (
    caminho_processual VARCHAR2(100) PRIMARY KEY
);
INSERT INTO caminho_processo (caminho_processual) VALUES ('Petição Inicial');
INSERT INTO caminho_processo (caminho_processual) VALUES ('Intimação');
INSERT INTO caminho_processo (caminho_processual) VALUES ('Contestação');
INSERT INTO caminho_processo (caminho_processual) VALUES ('Notificação');
INSERT INTO caminho_processo (caminho_processual) VALUES ('Conciliação');
INSERT INTO caminho_processo (caminho_processual) VALUES ('Sentença');
INSERT INTO caminho_processo (caminho_processual) VALUES ('Apelação');

select * from caminho_processo


-- Criar tabela dos dados do processo jurídico
CREATE TABLE processos_juridicos (
    numero_processo VARCHAR2(50) PRIMARY KEY,
    classe_processo VARCHAR2(100),
    rito_processo VARCHAR2(100),
    nome_advogado VARCHAR2(255),
    numero_oab VARCHAR2(50),
    nome_cliente_empresa VARCHAR2(255),
    caminho_processual VARCHAR2(100),
    nome_juiz VARCHAR2(255),
    estado_processo CHAR(2),
    valor_causa NUMBER,
    valor_deferido_causa NUMBER,
    valor_pago_causa NUMBER,
    observacoes_clob CLOB
);


-- Adicionando as colunas justiça e tribunal na coluna de dados dos processos
ALTER TABLE processos_juridicos
ADD (
    justica VARCHAR2(150),
    tribunal VARCHAR2(150)
);


CREATE TABLE arquivos_processos (
    id_arquivo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    numero_processo VARCHAR2(50),
    nome_arquivo VARCHAR2(255),
    arquivo_pdf BLOB,
    CONSTRAINT fk_processo
        FOREIGN KEY (numero_processo)
        REFERENCES processos_juridicos (numero_processo)
        ON DELETE CASCADE
);