-- Criando tabela de usuário de banco para administração
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE,
    password VARCHAR2(100),
    data_creiacao DATE DEFAULT SYSDATE
);

insert into users(username, password)
values('admin', 'admin');

select * from users;

ALTER TABLE users
ADD CONSTRAINT fk_username
FOREIGN KEY (username)
REFERENCES login_user_data(username)
ON DELETE CASCADE;


-- Criando tabela de cadastr do usuário, terá relação com a tela
CREATE TABLE login_user_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    login_password VARCHAR2(100) NOT NULL,
    num_oab VARCHAR2(20),
    username VARCHAR2(50) NOT NULL UNIQUE
);

insert into login_user_data(name, email, login_password, num_oab, username)
values('admin', 'admin@gmail.com', '1234', '0099887766', 'admin');

select * from login_user_data;


